name: Deployment

# on commit push, run job
on: [push]

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - name: 'Decrypt Secrets'
      run: sh ./.github/scripts/decrypt_secret.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: strava-calendar-summary
        runtime: python38
        entry_point: start
        timeout: 10
        max_instances: 3
        event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
        event_trigger_resource: projects/$PROJECT_ID/topics/StravaCalendarSummaryStravaWebhookEvents 
